async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "no"
enable_bucket = true
epoch = 3
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "exponential"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
keep_in_memory = true
learning_rate = 0.0002
loss_type = "huber"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 1536
max_data_loader_n_workers = 12
max_grad_norm = 1
max_timestep = 100
max_token_length = 225
max_train_steps = 200
min_bucket_reso = 384
min_snr_gamma = 5
mixed_precision = "bf16"
module_dropout = 0.1
network_alpha = 128
network_args = []
network_dim = 256
network_module = "networks.lora"
no_half_vae = false
noise_offset_type = "Multires"
optimizer_args = [ "weight_decay=0.01",]
optimizer_type = "Lion8bit"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
rank_dropout = 0.05
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_steps = 50
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = [ 1e-5, 1e-5,]
train_batch_size = 12
train_data_dir = ""
training_comment = ""
unet_lr = 0.0002
vae_batch_size = 16
xformers = true
validate_dataset = true
